# Generated by Django 5.1.7 on 2025-03-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("bank_id", models.AutoField(primary_key=True, serialize=False)),
                ("legal_address", models.TextField(verbose_name="Юридический адрес")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=255, verbose_name="Отчество"),
                ),
                ("phone_number", models.CharField(max_length=50, verbose_name="Номер")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="Дата")),
                ("amount", models.FloatField(verbose_name="Сумма")),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                ("deposit_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.FloatField(verbose_name="Сумма")),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Процентная ставка"
                    ),
                ),
                ("term", models.PositiveIntegerField(verbose_name="Срок")),
                ("opening_date", models.DateField(verbose_name="Дата открытия")),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата закрытия"
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="polls.bank",
                    ),
                ),
                (
                    "client_id1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="polls.client",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="polls.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="deposit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="polls.deposit",
            ),
        ),
    ]
